frontend:
  image:
    repository: registry.digitalocean.com/artifact-store/berlin-ionic
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: my-backend-image
  replicaCount: 2
  service:
    type: ClusterIP
    port: 3000

postgresql:
  image:
    repository: postgres
  service:
    type: ClusterIP
    port: 5432

controller:
  extraArgs:
    allow-snippet-annotations: "true"
  config:
    custom-http-errors: "404,403,500,502,503,504"
    use-forwarded-headers: "true"
  configMapNamespace: ingress-nginx
  configMap: nginx-config

