apiVersion: v1
kind: Service
metadata:
  name: berlin-api
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: berlin-api
  ports:
    - port: 80
      targetPort: 3000
