apiVersion: v1
kind: Service
metadata:
  name: berlin-ionic
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: berlin-ionic
  ports:
    - port: 80
      targetPort: 80
